name = "pm-empower-static"
main = "src/index.ts"
compatibility_date = "2023-09-22"
routes = [
	{ pattern = "static.pm-empower.com", custom_domain = true }
]
kv_namespaces = [
  { binding = "KV", id = "c6c564154ee44c728146dcde728c3a4c", preview_id = "c244e1d094dc433d9653ad666a687f6d" },
]
r2_buckets  = [
  { binding = "BUCKET", bucket_name = "statics-prod"}
]

[vars]
AUTH_AUDIENCE = "https://pm-empower.us.auth0.com/api/v2/"
AUTH_DOMAIN = "auth.pm-empower.com"
CORS_ORIGINS = "http://localhost:4200,https://test.pm-empower.com,https://app.pm-empower.com"
