name = "worker-ai"
main = "src/index.ts"
compatibility_date = "2023-09-22"
routes = [
	{ pattern = "ai.pm-empower.com", custom_domain = true }
]
kv_namespaces = [
  { binding = "KV", id = "c244e1d094dc433d9653ad666a687f6d", preview_id = "c244e1d094dc433d9653ad666a687f6d" },
]

[vars]
AI_GATEWAY = "test-gateway"
ALLOWED_USERS = "auth0|62a1187e776a0843f54c2c22,auth0|62a26ab9b5d49668f27fd502"
AUTH_AUDIENCE = "https://pm-empower.us.auth0.com/api/v2/"
AUTH_DOMAIN = "auth.pm-empower.com"
CORS_ORIGINS = "http://localhost:4200,https://library-demo.pm-empower.com,https://test.pm-empower.com,https://app.pm-empower.com"
