export enum FOOTER_VIEWS {
  BACK_CONTINUE = 'bc',
  CONTINUE_ONLY = 'c',
  CONTINUE_ONLY_CENTERED = 'c-c',
  BACK_ONLY = 'b',
  BACK_ONLY_CENTERED = 'b-c'
}
export type FOOTER_VIEWS_TYPE =
  | FOOTER_VIEWS.BACK_CONTINUE
  | FOOTER_VIEWS.CONTINUE_ONLY
  | FOOTER_VIEWS.CONTINUE_ONLY_CENTERED
  | FOOTER_VIEWS.BACK_ONLY
  | FOOTER_VIEWS.BACK_ONLY_CENTERED;
