import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { TranslateModule } from '@ngx-translate/core';
import { PageHeaderComponent, SwitchComponent } from './components';
import {
  EditorFixerDirective,
  FillElementDirective,
  MatchSizeDirective,
  ProgressBarDirective,
} from './directives';
import {
  CategoryIconPipe,
  CategoryIdConverterPipe,
  CategoryLabelListPipe,
  CategoryLabelPipe,
  DateTextPipe,
  DisciplineIconPipe,
  EditedDateTextPipe,
  JoinPipe,
  LengthPipe,
  ProjectListFilterLengthPipe,
  ProjectListFilterPipe,
  ProjectStatusPipe,
  RoleListPipe,
  SafeHtmlPipe,
  SafeUrlPipe,
  UserNamePipe,
  UserSortPipe,
  UsersPipe,
} from './pipes';

@NgModule({
  imports: [
    CommonModule,
    FontAwesomeModule,
    FormsModule,
    RouterModule,
    TranslateModule.forChild(),
  ],
  declarations: [
    CategoryIconPipe,
    CategoryIdConverterPipe,
    CategoryLabelListPipe,
    CategoryLabelPipe,
    DateTextPipe,
    DisciplineIconPipe,
    EditedDateTextPipe,
    EditorFixerDirective,
    FillElementDirective,
    JoinPipe,
    LengthPipe,
    MatchSizeDirective,
    PageHeaderComponent,
    ProgressBarDirective,
    ProjectListFilterPipe,
    ProjectListFilterLengthPipe,
    ProjectStatusPipe,
    RoleListPipe,
    SafeHtmlPipe,
    SafeUrlPipe,
    SwitchComponent,
    UserNamePipe,
    UserSortPipe,
    UsersPipe,
  ],
  exports: [
    CategoryIconPipe,
    CategoryIdConverterPipe,
    CategoryLabelListPipe,
    CategoryLabelPipe,
    CommonModule,
    DateTextPipe,
    DisciplineIconPipe,
    EditedDateTextPipe,
    EditorFixerDirective,
    FillElementDirective,
    FontAwesomeModule,
    FormsModule,
    JoinPipe,
    MatchSizeDirective,
    PageHeaderComponent,
    ProgressBarDirective,
    ProjectStatusPipe,
    RoleListPipe,
    SafeHtmlPipe,
    SafeUrlPipe,
    SwitchComponent,
    TranslateModule,
    UserNamePipe,
    UserSortPipe,
    UsersPipe,
  ],
})
export class SharedModule {}
