# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - worker/*

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

jobs:
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: "22.0"
      displayName: "Install Node.js"

    - script: npm install --global typescript
      displayName: "Install TypeScript"

    - script: npm run deploy:install
      workingDirectory: "worker"
      displayName: "Install"

    - script: npm run check
      workingDirectory: "worker"
      displayName: "Check"

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: "worker"
        includeRootFolder: false
        archiveType: "zip"
        archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-Worker.zip"
        replaceExistingArchive: true
      displayName: "Zip"

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: "$(Build.ArtifactStagingDirectory)"
        ArtifactName: "drop"
        publishLocation: "Container"
      displayName: "Publish"
