# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

jobs:
  - job: azure_job
    displayName: Azure Functions
    dependsOn: worker_job
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: "publish"
          publishWebProjects: false
          projects: "./_other/utilities/utilities.csproj"
          arguments: "-o ./_other/utilities/dist"
          zipAfterPublish: false
          modifyOutputPath: true
        displayName: "Build Azure Functions"

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: "_other/utilities/dist"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-Azure.zip"
          replaceExistingArchive: true
        displayName: "Zip Azure"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: "drop"
          publishLocation: "Container"
        displayName: "Publish Worker"

  - job: worker_job
    displayName: Worker
    dependsOn: site_job
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "18.10"
        displayName: "Install Node.js"

      - script: |
          yarn global add esbuild
        displayName: "Install ES Build"

      - script: yarn
        workingDirectory: "worker"
        displayName: "Install Worker Packages"

      - script: yarn run build
        workingDirectory: "worker"
        displayName: "Build Worker"

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: "worker"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-Worker.zip"
          replaceExistingArchive: true
        displayName: "Zip Worker"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: "drop"
          publishLocation: "Container"
        displayName: "Publish Worker"

  - job: resource_job
    displayName: Resources
    steps:
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: "_other/data/files/resources-*.json"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-Resources.zip"
          replaceExistingArchive: true
        displayName: "Zip"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: "drop"
          publishLocation: "Container"
        displayName: "Publish"
