# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: setup_job
    displayName: Setup
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "18.10"
        displayName: "Install Node.js"

      - script: npx kendo-ui-license activate
        workingDirectory: "site"
        env:
          KENDO_UI_LICENSE: $(KENDO_UI_LICENSE)
        displayName: "Activate Kendo UI License"

      - script: |
          yarn global add @angular/cli
          yarn
        workingDirectory: "site"
        displayName: "Install Site Packages"

      - script: yarn run setup
        workingDirectory: "worker"
        displayName: "Install Worker Packages"

  - job: worker_job
    displayName: Worker
    dependsOn: setup_job
    steps:
      - script: yarn run build
        workingDirectory: "worker"
        displayName: "Build Worker"

  - job: prod_job
    displayName: Production Build
    dependsOn: worker_job
    steps:
      - script: yarn run deploy
        workingDirectory: "site"
        displayName: "Build Site"
