# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - server/*
      - azure-pipelines-api.yml
variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

pool:
  vmImage: ubuntu-latest

jobs:
  steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: "publish"
        publishWebProjects: false
        projects: "./server/api/api.csproj"
        arguments: "-o ./server/api/dist"
        zipAfterPublish: false
        modifyOutputPath: true
      displayName: "Build"

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: "server/api/dist/api"
        includeRootFolder: false
        archiveType: "zip"
        archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-Api.zip"
        replaceExistingArchive: true
      displayName: "Zip"

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: "$(Build.ArtifactStagingDirectory)"
        ArtifactName: "drop"
        publishLocation: "Container"
      displayName: "Publish"
