# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: setup_job
    displayName: Setup
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "18.10"
        displayName: "Install Node.js"

      - script: npm config set "@fortawesome:registry" https://npm.fontawesome.com/
        workingDirectory: "site"
        env:
          KENDO_UI_LICENSE: $(KENDO_UI_LICENSE)
        displayName: "Setup Kendo UI Registry"

      - script: yarn global add @angular/cli
        workingDirectory: "site"
        displayName: "Install Angular CLI"

      - script: yarn
        workingDirectory: "site"
        displayName: "Install Site Packages"

      - script: yarn
        workingDirectory: "worker"
        displayName: "Install Worker Packages"

      - script: npx kendo-ui-license activate
        workingDirectory: "site"
        env:
          KENDO_UI_LICENSE: $(KENDO_UI_LICENSE)
        displayName: "Setup Kendo UI License"

  - job: worker_job
    displayName: Worker
    dependsOn: setup_job
    steps:
      - script: yarn run build
        workingDirectory: "worker"
        displayName: "Build Worker"

  - job: prod_job
    displayName: Production Build
    dependsOn: worker_job
    steps:
      - script: yarn run deploy
        workingDirectory: "site"
        displayName: "Build Site"
