version: '3'
services:
  web-api:
    container_name: web-api
    build:
      context: ./api
      dockerfile: Dockerfile-dev
    ports:
      - 5216:5216
    volumes:
      - './api:/usr/src/app/api'
  
  auth-api:
    container_name: auth-api
    build:
      context: ./auth-api
      dockerfile: Dockerfile-dev
    ports:
      - 8080:8080
    volumes:
      - './auth-api:/usr/src/app/auth-api'
  
  worker:
    container_name: worker
    build:
      context: ./worker
      dockerfile: Dockerfile-dev
    ports:
      - 88:88
    volumes:
       - ./worker:/usr/src/app/worker
       - /usr/src/app/worker/node_modules

  site:
    container_name: site
    build:
      context: ./site
      dockerfile: Dockerfile-dev
      args:
          FA_TOKEN: $FA_TOKEN
          KENDO_UI_LICENSE: $KENDO_UI_LICENSE
    ports:
      - 4200:4200
    volumes:
       - ./site:/usr/src/app/site
       - /usr/src/app/site/node_modules
