name: pm-empower
services:
  wbs-api:
    container_name: wbs-api
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    ports:
      - 5216:5216
    volumes:
      - './server:/usr/src/app'
  
  wbs-worker:
    container_name: wbs-worker
    build:
      context: ./worker
      dockerfile: Dockerfile-dev
    ports:
      - 88:88
    volumes:
       - ./worker:/usr/src/app/worker

  wbs-site:
    container_name: wbs-site
    build:
      context: ./site
      dockerfile: Dockerfile-dev
      args:
          FA_TOKEN: $FA_TOKEN
          KENDO_UI_LICENSE: $KENDO_UI_LICENSE
    ports:
      - 4200:4200
    volumes:
       - ./site:/usr/src/app/site
       - /usr/src/app/site/node_modules

  #wbs-db:
  #  image: mcr.microsoft.com/mssql/server:2022-latest
  #  ports:
  #    - 1433:1433
  #  volumes:
  #    - ./_db/data:/var/opt/mssql/data
  #    - ./_db/log:/var/opt/mssql/log
  #    - ./_db/secrets:/var/opt/mssql/secrets
  #  environment:
  #    - ACCEPT_EULA=Y

volumes:
  share:
    external: true