version: '3'
services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile-dev
    ports:
      - 5216:5216
    volumes:
      - './api:/usr/src/app/api'
  
  worker:
    container_name: worker
    build:
      context: ./worker
      dockerfile: Dockerfile-dev
    ports:
      - "88:88"
    volumes:
       - ./worker:/usr/src/app/worker
       - /usr/src/app/worker/node_modules

  site:
    container_name: site
    build:
      context: ./site
      dockerfile: Dockerfile-dev
      args:
          FA_TOKEN: $FA_TOKEN
          KENDO_UI_LICENSE: $KENDO_UI_LICENSE
    ports:
      - "4200:4200"
    volumes:
       - ./site:/usr/src/app/site
       - /usr/src/app/site/node_modules
