services:
  wbs-api:
    container_name: wbs-api
    build:
      context: ./server/api
      dockerfile: Dockerfile-dev
    ports:
      - 5216:5216
    volumes:
      - './server/core:/usr/src/app/core'
      - './server/api:/usr/src/app/api'
  
  wbs-worker:
    container_name: wbs-worker
    build:
      context: ./server/worker
      dockerfile: Dockerfile-dev
    ports:
      - 88:88
    volumes:
       - ./server/worker:/usr/src/app/worker

  wbs-site:
    container_name: wbs-site
    build:
      context: ./site/app
      dockerfile: Dockerfile-dev
      args:
          FA_TOKEN: $FA_TOKEN
          KENDO_UI_LICENSE: $KENDO_UI_LICENSE
    #ports:
    #  - 4200:4200
    volumes:
       - ./site/app:/usr/src/app/site
       - /usr/src/app/site/node_modules
       - shared-volume:/usr/src/app/site/dist

  wbs-pages:
    container_name: wbs-pages
    build:
      context: ./site/pages
      dockerfile: Dockerfile-dev
    ports:
      - 4200:4200
    volumes:
       - ./site/pages:/usr/src/app/pages
       - shared-volume:/usr/src/app/pages/dist

volumes:
  shared-volume: