version: '3'
services:
  local.storage.emulator:
      image: "mcr.microsoft.com/azure-storage/azurite:latest"
      container_name: local.storage.emulator
      ports:
          - 10000:10000
          - 10001:10001

  wbs.functions:
    container_name: wbs-functions
    build:
        context: ./api
        dockerfile: Dockerfile
    ports:
        - 7071:7071
    #environment:
        # Copy .env variables through to container
        #- AzureWebJobsStorage
        #- BlobContainerName
        #- BlobOutputContainerName
        #- QueueName
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/api/Bin
       - /usr/src/api/Obj
    #depends_on:
       #- local.storage.emulator

  wbs-worker:
    build:
      context: ./worker
      dockerfile: Dockerfile-dev
    ports:
      - "88:88"
    container_name: wbs-worker
    volumes:
       - ./worker:/usr/src/app/worker
       - /usr/src/app/worker/node_modules
  wbs-site:
    build:
      context: ./site
      dockerfile: Dockerfile-dev
      args:
          FA_TOKEN: $FA_TOKEN
          KENDO_UI_LICENSE: $KENDO_UI_LICENSE
    ports:
      - "4200:4200"
    container_name: wbs-site
    volumes:
       - ./site:/usr/src/app/site
       - /usr/src/app/site/node_modules
# wbs-util:
#    build:
#      context: ./_other/utilities
#      dockerfile: Dockerfile-dev
#    ports:
#      - "7071:7071"
#    container_name: wbs-util
#    volumes:
#       - ./_other/utilities:/usr/src/app/utilities
#       - /usr/src/app/utilities/Bin
#       - /usr/src/app/utilities/Obj