name: pm-empower
services:
  wbs-api:
    container_name: wbs-api
    build:
      context: ./server
      dockerfile: ./api/Dockerfile-dev
    ports:
      - 5216:5216
    volumes:
      - './server:/usr/src/app'
  
  wbs-worker:
    container_name: wbs-workers
    build:
      context: ./server/workers
      dockerfile: Dockerfile-dev
    ports:
      - 88:88
    volumes:
       - ./server/workers:/usr/src/app/workers/
       #- ./server/workers/data:/usr/src/app/workers/.data
       #- worker_data:/usr/src/app/workers/.data

  wbs-site:
    container_name: wbs-site
    build:
      context: ./site
      dockerfile: Dockerfile-dev
      args:
          FA_TOKEN: $FA_TOKEN
          KENDO_UI_LICENSE: $KENDO_UI_LICENSE
    ports:
      - 4200:4200
    volumes:
       - ./site:/usr/src/app/site
       - /usr/src/app/site/node_modules

volumes:
  share:
    external: true