# Stage 1
FROM node:20.11.0 as node

WORKDIR /usr/src/app/site

COPY ./ ./

ARG FA_TOKEN
ARG KENDO_UI_LICENSE

ENV FA_TOKEN=${FA_TOKEN}
ENV KENDO_UI_LICENSE=${KENDO_UI_LICENSE}

RUN npm run docker:globals
RUN npm run docker:fa ${FA_TOKEN}
RUN npm run docker:install
RUN npm run kendo:auth

EXPOSE 4200

CMD ["npm", "start"]
