name = "pm-empower-site"
compatibility_date = "2024-05-13"
pages_build_output_dir = "./dist"

[vars]
APP_TITLE = "PM Empower"
CAN_TEST_AI = "auth0|62a1187e776a0843f54c2c22,auth0|62a26ab9b5d49668f27fd502"

[dev]
port = 4200
ip = "*"
