export enum LIBRARY_VERSION_ACTIONS {
  ENTRY_CREATED = 'library-entry-created',
  CREATED = 'library-version-created',
  TITLE_CHANGED = 'library-version-title-changed',
  VERSION_ALIAS_CHANGED = 'library-version-alias-changed',
  CATEGORY_CHANGED = 'library-version-category-changed',
  DESCRIPTION_CHANGED = 'library-version-description-changed',
  DISCIPLINES_CHANGED = 'library-version-disciplines-changed',
  SETUP_PHASE = 'library-version-phase-setup',
  SETUP_TASK = 'library-version-task-task-setup',
  UPLOAD = 'library-version-upload',
  PUBLISHED = 'library-version-published',
  UNPUBLISHED = 'library-version-unpublished',
  CANCEL_VERSION = 'library-version-cancel',
  CONTRIBUTORS_CHANGED = 'library-version-contributors-changed',
  RESOURCE_ADDED = 'library-version-resources-added',
  RESOURCE_CHANGED = 'library-version-resource-changed',
  RESOURCE_REMOVED = 'library-version-resource-removed',
  RESOURCE_REORDERED = 'library-version-resource-reordered',
  IMPORT_TASKS = 'library-version-import-tasks',
}
