name = "wbs-auth"
account_id = "004dc1af737b22a8aa83b3550fa9b9d3"
compatibility_date = "2022-05-27"
main = "dist/index.js"

[build]
command = "yarn run -s build"

[build.upload]
format = "modules"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[env.dev]
name = "auth"
kv_namespaces = [
  { binding = "KV_AUTH" },
]

[env.qa]
name = "app-v0-1-auth-qa"
workers_dev = false
kv_namespaces = [
  { binding = "KV_AUTH", id = "6eb87b9b5d9f4261907b80164cbc0947", preview_id = "6eb87b9b5d9f4261907b80164cbc0947" },
]

[env.prod]
name = "app-v0-1-auth-prod"
workers_dev = false
kv_namespaces = [
  { binding = "KV_AUTH", id = "10409096739e4b648c2af52e2d16065c", preview_id = "10409096739e4b648c2af52e2d16065c" },
]

[miniflare]
port = 88
watch = true
kv_persist = "../.mf/kv/"
