name = "wbs-app"
account_id = "004dc1af737b22a8aa83b3550fa9b9d3"
compatibility_date = "2022-05-27"
main = "dist/index.js"

[build]
command = "yarn run -s build"

[build.upload]
format = "modules"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[env.dev]
name = "api"
usage_model = "unbound"
kv_namespaces = [
  { binding = "KV_AUTH" },
  { binding = "KV_DATA" },
]
r2_buckets = [
  { binding = "BUCKET_SNAPSHOTS" },
  { binding = "BUCKET_STATICS" },
]
services = [
  { binding = "AUTH_WORKER", service = "auth" }
]
vars = { APP_INSIGHTS_KEY = "1a9b6a54-3afc-4ee5-8e17-3d109b834c55", DEBUG = "true" }

[env.qa]
name = "app-v0.1-api-qa"
usage_model = "unbound"
workers_dev = false
routes = [
  { pattern = "app-test.thewbsproject.com/*", zone_id = "5c2549bae0a35fb59176d4a54e5a717a" }
]
kv_namespaces = [
  { binding = "KV_AUTH", id = "6eb87b9b5d9f4261907b80164cbc0947", preview_id = "6eb87b9b5d9f4261907b80164cbc0947" },
  { binding = "KV_DATA", id = "6a8e3a3a07014e228d56aa7f28059ed2", preview_id = "6a8e3a3a07014e228d56aa7f28059ed2" },
]
r2_buckets = [
  { binding = "BUCKET_SNAPSHOTS", bucket_name = "snapshots-qa" }
]
vars = { CORS_URLS = "https://app-test.thewbsproject.com", APP_INSIGHTS_KEY = "5a16ddbc-8131-4627-8497-1c4977cb7730" }

[env.prod]
name = "app-v0.1-api-prod"
usage_model = "unbound"
workers_dev = false
routes = [
  { pattern = "app.thewbsproject.com/*", zone_id = "5c2549bae0a35fb59176d4a54e5a717a" }
]
kv_namespaces = [
  { binding = "KV_AUTH", id = "10409096739e4b648c2af52e2d16065c", preview_id = "10409096739e4b648c2af52e2d16065c" },
  { binding = "KV_DATA", id = "408389bba37f437da346442f36b25a45", preview_id = "408389bba37f437da346442f36b25a45" },
]
r2_buckets = [
  { binding = "BUCKET_SNAPSHOTS", bucket_name = "snapshots-prod" }
]
vars = { CORS_URLS = "https://app.thewbsproject.com", APP_INSIGHTS_KEY = "5a16ddbc-8131-4627-8497-1c4977cb7730" }

[miniflare]
port = 88
upstream = "http://localhost:4200"
watch = true
kv_persist = true
r2_persist = true
cache_persist = false
cache = false
https = false
actual_time = true
inaccurate_cpu = true

[miniflare.mounts]
auth = "../auth@dev"
