name = "pm-empower-auth"
account_id = "004dc1af737b22a8aa83b3550fa9b9d3"
compatibility_date = "2024-05-02"
main = "src/index.ts"
workers_dev = false
logpush = true

[placement]
mode = "smart"

[env.dev]
name = "pm-empower-auth-dev"
kv_namespaces = [
  { binding = "KV_DATA", id = "00827b33acf94d819417a2625e36b4b5", preview_id = "5af4598e11804d4aaa0de359a55c6453" },
]

[env.dev.vars]
DATADOG_ENV = "development"
DATADOG_HOST = "auth-api.pm-empower.com"
AUTH_DOMAIN = "auth.pm-empower.com"
AUTH_AUDIENCE = "https://pm-empower.us.auth0.com/api/v2/"
CORS_ORIGINS = "http://localhost:4200,https://test.pm-empower.com,https://app.pm-empower.com"

[env.test]
name = "pm-empower-auth-test"
workers_dev = false
kv_namespaces = [
  { binding = "KV_DATA", id = "e8f2ec367ae74d309737ca76a34055a9", preview_id = "5af4598e11804d4aaa0de359a55c6453" },
]

[env.test.vars]
DATADOG_ENV = "test"
DATADOG_HOST = "test-api.pm-empower.com"
CORS_ORIGINS = "https://test.pm-empower.com"
AUTH_DOMAIN = "auth.pm-empower.com"
AUTH_AUDIENCE = "https://pm-empower.us.auth0.com/api/v2/"

[env.prod]
name = "pm-empower-auth-prod"
workers_dev = false
kv_namespaces = [
  { binding = "KV_DATA", id = "4d97dfa226134e77862c476a360bb8cb", preview_id = "5af4598e11804d4aaa0de359a55c6453" },
]

[env.prod.vars]
DATADOG_ENV = "production"
DATADOG_HOST = "api.pm-empower.com"
CORS_ORIGINS = "https://app.pm-empower.com"
AUTH_DOMAIN = "auth.pm-empower.com"
AUTH_AUDIENCE = "https://pm-empower.us.auth0.com/api/v2/"

[dev]
port = 8080
ip = "*"
