# Stage 1
FROM node:18.16.1 as node

WORKDIR /usr/src/app/worker

COPY . .

RUN npm install -g wrangler --unsafe-perm true
RUN npm install
#RUN yarn global add wrangler@latest && yarn

EXPOSE 88

CMD ["npm", "start"]
