name = "pm-empower-api"
account_id = "004dc1af737b22a8aa83b3550fa9b9d3"
compatibility_date = "2024-05-02"
main = "src/index.ts"
logpush = true

[env.dev]
name = "pm-empower-api-dev"
usage_model = "unbound"
kv_namespaces = [
  { binding = "KV_DATA", id = "123" },
]
services = [
  { binding = "AUTH_API_ROLES", service = "pm-empower-auth-dev", entrypoint = "RolesEntrypoint" },
  { binding = "AUTH_API_USERS", service = "pm-empower-auth-dev", entrypoint = "UserEntrypoint" },
  { binding = "AUTH_API_QUEUES", service = "pm-empower-auth-dev", entrypoint = "QueueEntrypoint" },
  { binding = "AUTH_API_INVITES", service = "pm-empower-auth-dev", entrypoint = "InviteEntrypoint" },
  { binding = "AUTH_API_MEMBERSHIPS", service = "pm-empower-auth-dev", entrypoint = "MembershipsEntrypoint" },
  { binding = "AUTH_API_ORGANIZATIONS", service = "pm-empower-auth-dev", entrypoint = "OrganizationEntrypoint" }
]

[env.queues]
producers = [{ binding = "QUEUE_REFRESH_ALL", queue = "auth-refresh-all" }]
consumers = [{ queue = "auth-refresh-all", max_batch_size = 1, max_batch_timeout = 30, max_retries = 5, dead_letter_queue = "auth-refresh-all-dlq", max_concurrency = 5, retry_delay = 120 }]


[env.dev.vars]
DEBUG = "true"
DATADOG_ENV = "development"
DATADOG_HOST = "localhost:88"
CORS_ORIGINS = "http://localhost:4200"
KV_BYPASS = "LISTS"
MAILGUN_ENDPOINT = "https://api.mailgun.net/v3/mg.thewbsproject.com"
AUTH_AUDIENCE = "https://pm-empower.us.auth0.com/api/v2/"
AUTH_DOMAIN = "auth.pm-empower.com"
JIRA_EMAIL = "chriswalton@cwsoftware.biz"
JIRA_DOMAIN = "cw-software.atlassian.net"

[env.test]
name = "pm-empower-api-test"
usage_model = "unbound"
workers_dev = false
routes = [
	{ pattern = "test-api.pm-empower.com/*", zone_name = "pm-empower.com" }
]
kv_namespaces = [
  { binding = "KV_DATA", id = "e8f2ec367ae74d309737ca76a34055a9", preview_id = "5af4598e11804d4aaa0de359a55c6453" },
]
services = [
  { binding = "AUTH_API_ROLES", service = "pm-empower-auth-test", entrypoint = "RolesEntrypoint" },
  { binding = "AUTH_API_USERS", service = "pm-empower-auth-test", entrypoint = "UserEntrypoint" },
  { binding = "AUTH_API_QUEUES", service = "pm-empower-auth-test", entrypoint = "QueueEntrypoint" },
  { binding = "AUTH_API_INVITES", service = "pm-empower-auth-test", entrypoint = "InviteEntrypoint" },
  { binding = "AUTH_API_MEMBERSHIPS", service = "pm-empower-auth-test", entrypoint = "MembershipsEntrypoint" },
  { binding = "AUTH_API_ORGANIZATIONS", service = "pm-empower-auth-test", entrypoint = "OrganizationEntrypoint" }
]

[env.test.vars]
DEBUG = "false"
DATADOG_ENV = "test"
DATADOG_HOST = "test-api.pm-empower.com"
CORS_ORIGINS = "https://test.pm-empower.com"
MAILGUN_ENDPOINT = "https://api.mailgun.net/v3/mg.thewbsproject.com"
AUTH_AUDIENCE = "https://pm-empower.us.auth0.com/api/v2/"
AUTH_DOMAIN = "auth.pm-empower.com"

[env.prod]
name = "pm-empower-api-prod"
usage_model = "unbound"
workers_dev = false
routes = [
	{ pattern = "api.pm-empower.com/*", zone_name = "pm-empower.com" }
]
kv_namespaces = [
  { binding = "KV_DATA", id = "4d97dfa226134e77862c476a360bb8cb", preview_id = "5af4598e11804d4aaa0de359a55c6453" },
]
services = [
  { binding = "AUTH_API_ROLES", service = "pm-empower-auth-test", entrypoint = "RolesEntrypoint" },
  { binding = "AUTH_API_USERS", service = "pm-empower-auth-test", entrypoint = "UserEntrypoint" },
  { binding = "AUTH_API_QUEUES", service = "pm-empower-auth-test", entrypoint = "QueueEntrypoint" },
  { binding = "AUTH_API_INVITES", service = "pm-empower-auth-test", entrypoint = "InviteEntrypoint" },
  { binding = "AUTH_API_MEMBERSHIPS", service = "pm-empower-auth-test", entrypoint = "MembershipsEntrypoint" },
  { binding = "AUTH_API_ORGANIZATIONS", service = "pm-empower-auth-test", entrypoint = "OrganizationEntrypoint" }
]

[env.prod.vars]
DEBUG = "false"
DATADOG_ENV = "production"
DATADOG_HOST = "api.pm-empower.com"
CORS_ORIGINS = "https://app.pm-empower.com"
MAILGUN_ENDPOINT = "https://api.mailgun.net/v3/mg.thewbsproject.com"
AUTH_AUDIENCE = "https://pm-empower.us.auth0.com/api/v2/"
AUTH_DOMAIN = "auth.pm-empower.com"

[dev]
port = 88
host = "wbs-api"
ip = "*"
