export enum TASK_ACTIONS {
  CREATED = 'task-created',
  TITLE_CHANGED = 'task-title-changed',
  DESCRIPTION_CHANGED = 'task-description-changed',
  DISCIPLINES_CHANGED = 'task-disciplines-changed',
  ABS_CHANGED = 'task-abs-changed',
  CLONED = 'task-cloned',
  REORDERED = 'task-reordered',
  REMOVED = 'task-removed',
  RESOURCE_ADDED = 'task-resource-added',
  RESOURCE_UPDATED = 'task-resource-updated',
  RESOURCE_REMOVED = 'task-resource-removed',
  RESOURCE_REORDERED = 'task-resource-reordered',
  IMPORTED = 'task-imported',
}
