export enum PROJECT_ACTIONS {
  CREATED = 'project-created',
  UPLOADED = 'project-uploaded',
  TITLE_CHANGED = 'project-title-changed',
  DESCRIPTION_CHANGED = 'project-description-changed',
  CATEGORY_CHANGED = 'project-category-changed',
  PHASES_CHANGED = 'project-phases-changed',
  DISCIPLINES_CHANGED = 'project-disciplines-changed',
  ADDED_USER = 'project-added-user',
  REMOVED_USER = 'project-removed-user',
  STATUS_CHANGED = 'project-status-changed',
  IMPORTED_NODE_FROM_LIBRARY = 'project-imported-from-library',
  RESOURCE_ADDED = 'project-resource-added',
  RESOURCE_UPDATED = 'project-resource-updated',
  RESOURCE_REORDERED = 'project-resource-reordered',
  RESOURCE_REMOVED = 'project-resource-removed',
  CANCELLED = 'project-cancelled',
}
