export enum PROJECT_CREATION_PAGES {
  GETTING_STARTED = 1,
  BASICS = 2,
  SCOPE = 3,
  LIB_OR_SCRATCH = 4,
  LIB_SEARCH = 5,
  NODE_VIEW = 6,
  PHASES = 7,
  DESCIPLINES = 8,
  SAVING = 9,
}
export type PROJECT_CREATION_PAGES_TYPE =
  | PROJECT_CREATION_PAGES.GETTING_STARTED
  | PROJECT_CREATION_PAGES.BASICS
  | PROJECT_CREATION_PAGES.SCOPE
  | PROJECT_CREATION_PAGES.LIB_OR_SCRATCH
  | PROJECT_CREATION_PAGES.LIB_SEARCH
  | PROJECT_CREATION_PAGES.NODE_VIEW
  | PROJECT_CREATION_PAGES.PHASES
  | PROJECT_CREATION_PAGES.DESCIPLINES
  | PROJECT_CREATION_PAGES.SAVING;
