import { LIBRARY_CLAIMS } from './library-claims.const';
import { LIBRARY_ROLES } from './library-roles.const';
import { Permissions } from './permissions.type';

const permissions: Permissions = {};
const ROLES = LIBRARY_ROLES;

permissions[LIBRARY_CLAIMS.READ] = [ROLES.OWNER, ROLES.EDITOR, ROLES.VIEWER];
permissions[LIBRARY_CLAIMS.UPDATE] = [ROLES.OWNER, ROLES.EDITOR];
permissions[LIBRARY_CLAIMS.DELETE] = [ROLES.OWNER];

permissions[LIBRARY_CLAIMS.SETTINGS.READ] = [ROLES.OWNER, ROLES.EDITOR];

permissions[LIBRARY_CLAIMS.TASKS.READ] = [ROLES.OWNER, ROLES.EDITOR, ROLES.VIEWER];
permissions[LIBRARY_CLAIMS.TASKS.CREATE] = [ROLES.OWNER, ROLES.EDITOR];
permissions[LIBRARY_CLAIMS.TASKS.UPDATE] = [ROLES.OWNER, ROLES.EDITOR];
permissions[LIBRARY_CLAIMS.TASKS.DELETE] = [ROLES.OWNER, ROLES.EDITOR];

permissions[LIBRARY_CLAIMS.ROLES.READ] = [ROLES.OWNER, ROLES.EDITOR];
permissions[LIBRARY_CLAIMS.ROLES.CREATE] = [ROLES.OWNER];
permissions[LIBRARY_CLAIMS.ROLES.UPDATE] = [ROLES.OWNER];
permissions[LIBRARY_CLAIMS.ROLES.DELETE] = [ROLES.OWNER];

permissions[LIBRARY_CLAIMS.RESOURCES.READ] = [ROLES.OWNER, ROLES.EDITOR, ROLES.VIEWER];
permissions[LIBRARY_CLAIMS.RESOURCES.CREATE] = [ROLES.OWNER, ROLES.EDITOR];
permissions[LIBRARY_CLAIMS.RESOURCES.UPDATE] = [ROLES.OWNER, ROLES.EDITOR];
permissions[LIBRARY_CLAIMS.RESOURCES.DELETE] = [ROLES.OWNER, ROLES.EDITOR];

permissions[LIBRARY_CLAIMS.STATI.CAN_PUBLISH] = [ROLES.OWNER];

export const LIBRARY_PERMISSIONS = permissions;
