name = "pm-empower-api"
account_id = "004dc1af737b22a8aa83b3550fa9b9d3"
compatibility_date = "2022-05-27"
main = "src/index.ts"

[triggers]
crons = ["0 0 */1 * *"]

[env.dev]
name = "pm-empower-api-dev"
usage_model = "unbound"
kv_namespaces = [
  { binding = "KV_AUTH", id = "123", preview_id = "10044f1ce15740fd8cc0b2eaf11ca660" },
  { binding = "KV_DATA", id = "123", preview_id = "338c0ca3e3164ddf84b761218a121aa0" },
]
r2_buckets = [
  { binding = "BUCKET_SNAPSHOTS", bucket_name = "123", preview_bucket_name = "snapshots-dev" },
  { binding = "BUCKET_STATICS", bucket_name = "123", preview_bucket_name = "statics-dev" },
]
[env.dev.vars]
DEBUG = "true"
DATADOG_ENV = "development"
CORS_ORIGINS = "http://localhost:4200"
INVITE_TEMPLATE_ID = "invite-template-v1"
KV_BYPASS = "LISTS"

AZURE_ENDPOINT = "http://localhost:7071"
COSMOS_ENDPOINT = "https://wbs-dev-asia.documents.azure.com"
MAILGUN_ENDPOINT = "https://api.mailgun.net/v3/mg.thewbsproject.com"

COSMOS_DB = "combined"

AUTH_AUDIENCE = "https://pm-empower.us.auth0.com/api/v2/"
AUTH_CLIENT_ID = "zfvKgtPltxHsUGNPMYvF6JRljlp6xDuC"
AUTH_CONNECTION = "Username-Password-Authentication"
AUTH_DOMAIN = "pm-empower.us.auth0.com"

[env.test]
name = "pm-empower-api-test"
usage_model = "unbound"
workers_dev = false
routes = [
	{ pattern = "api-test.pm-empower.com", custom_domain = true, zone_name = "pm-empower.com" }
]
kv_namespaces = [
  { binding = "KV_AUTH", id = "6eb87b9b5d9f4261907b80164cbc0947", preview_id = "6eb87b9b5d9f4261907b80164cbc0947" },
  { binding = "KV_DATA", id = "6a8e3a3a07014e228d56aa7f28059ed2", preview_id = "6a8e3a3a07014e228d56aa7f28059ed2" },
]
r2_buckets = [
  { binding = "BUCKET_SNAPSHOTS", bucket_name = "snapshots-qa" }
]
[env.test.vars]
DEBUG = "false"
DATADOG_ENV = "test"
CORS_ORIGINS = "https://test.pm-empower.com"
INVITE_TEMPLATE_ID = "invite-template-v1"

AZURE_ENDPOINT = "https://pm-empower-test.azurewebsites.net"
COSMOS_ENDPOINT = "https://wbs-qa.documents.azure.com"
MAILGUN_ENDPOINT = "https://api.mailgun.net/v3/mg.thewbsproject.com"

AUTH_AUDIENCE = "https://dev-3lcexa83.us.auth0.com/api/v2/"
AUTH_CLIENT_ID = "FxJs3MltLs4hGSTUwDauuindOUPNjwuG"
AUTH_CONNECTION = "acme-engineering"
AUTH_DOMAIN = "auth.dev.thewbsproject.com"

[env.prod]
name = "pm-empower-api-prod"
usage_model = "unbound"
workers_dev = false
routes = [
	{ pattern = "api.pm-empower.com", custom_domain = true, zone_name = "pm-empower.com" }
]
kv_namespaces = [

  { binding = "KV_AUTH", id = "10409096739e4b648c2af52e2d16065c", preview_id = "10409096739e4b648c2af52e2d16065c" },
  { binding = "KV_DATA", id = "408389bba37f437da346442f36b25a45", preview_id = "408389bba37f437da346442f36b25a45" },
]
r2_buckets = [
  { binding = "BUCKET_SNAPSHOTS", bucket_name = "snapshots-prod.com" }
]
[env.prod.vars]
DEBUG = "false"
DATADOG_ENV = "production"
CORS_ORIGINS = "http://localhost:4200"
INVITE_TEMPLATE_ID = "invite-template-v1"

AZURE_ENDPOINT = "https://wbs-v0-1-prod.azurewebsites.net"
COSMOS_ENDPOINT = "https://wbs-qa.documents.azure.com"
MAILGUN_ENDPOINT = "https://api.mailgun.net/v3/mg.thewbsproject.com"

AUTH_AUDIENCE = "https://dev-3lcexa83.us.auth0.com/api/v2/"
AUTH_CLIENT_ID = "FxJs3MltLs4hGSTUwDauuindOUPNjwuG"
AUTH_CONNECTION = "acme-engineering"
AUTH_DOMAIN = "auth.dev.thewbsproject.com"

[dev]
port = 88
