name = "wbs-app"
account_id = "004dc1af737b22a8aa83b3550fa9b9d3"
compatibility_date = "2022-05-27"
main = "dist/index.js"

[build]
command = "yarn run -s build"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[triggers]
crons = ["0 0 */1 * *"]

[env.dev]
name = "api"
usage_model = "unbound"
kv_namespaces = [
  { binding = "KV_AUTH", id = "123", preview_id = "10044f1ce15740fd8cc0b2eaf11ca660" },
  { binding = "KV_DATA", id = "123", preview_id = "338c0ca3e3164ddf84b761218a121aa0" },
]
r2_buckets = [
  { binding = "BUCKET_SNAPSHOTS", bucket_name = "123", preview_bucket_name = "snapshots-dev" },
  { binding = "BUCKET_STATICS", bucket_name = "123", preview_bucket_name = "statics-dev" },
]
vars = { DEBUG = "true", INVITE_TEMPLATE = "invite-template-v1",  APP_INSIGHTS_KEY = "44521f2e-90b6-4be0-8659-0c84bfde1907" }

[env.qa]
name = "app-v0-1-api-qa"
usage_model = "unbound"
workers_dev = false
routes = [
  { pattern = "app-test.thewbsproject.com/*", zone_id = "5c2549bae0a35fb59176d4a54e5a717a" }
]
kv_namespaces = [
  { binding = "KV_AUTH", id = "6eb87b9b5d9f4261907b80164cbc0947", preview_id = "6eb87b9b5d9f4261907b80164cbc0947" },
  { binding = "KV_DATA", id = "6a8e3a3a07014e228d56aa7f28059ed2", preview_id = "6a8e3a3a07014e228d56aa7f28059ed2" },
]
r2_buckets = [
  { binding = "BUCKET_SNAPSHOTS", bucket_name = "snapshots-qa" }
]
vars = { CORS_URLS = "https://app-test.thewbsproject.com", APP_INSIGHTS_KEY = "1f200dd0-488f-4e6d-900b-19c87a45d0b2" }

[env.prod]
name = "app-v0-1-api-prod"
usage_model = "unbound"
workers_dev = false
routes = [
  { pattern = "app.thewbsproject.com/*", zone_id = "5c2549bae0a35fb59176d4a54e5a717a" }
]
kv_namespaces = [
  { binding = "KV_AUTH", id = "10409096739e4b648c2af52e2d16065c", preview_id = "10409096739e4b648c2af52e2d16065c" },
  { binding = "KV_DATA", id = "408389bba37f437da346442f36b25a45", preview_id = "408389bba37f437da346442f36b25a45" },
]
r2_buckets = [
  { binding = "BUCKET_SNAPSHOTS", bucket_name = "snapshots-prod" }
]
vars = { CORS_URLS = "https://app.thewbsproject.com", APP_INSIGHTS_KEY = "5a16ddbc-8131-4627-8497-1c4977cb7730" }

[dev]
port = 88
host = "localhost:4200"
