name = "pm-empower-api"
account_id = "004dc1af737b22a8aa83b3550fa9b9d3"
compatibility_date = "2022-05-27"
main = "src/index.ts"

[triggers]
crons = ["0 0 */1 * *"]

[env.dev]
name = "pm-empower-api-dev"
usage_model = "unbound"
kv_namespaces = [
  { binding = "KV_DATA", id = "123", preview_id = "338c0ca3e3164ddf84b761218a121aa0" },
]
r2_buckets = [
  { binding = "BUCKET_SNAPSHOTS", bucket_name = "123", preview_bucket_name = "snapshots-dev" },
  { binding = "BUCKET_STATICS", bucket_name = "123", preview_bucket_name = "statics-dev" },
]

[env.dev.vars]
DEBUG = "true"
DATADOG_ENV = "development"
CORS_ORIGINS = "http://localhost:4200"
KV_BYPASS = "LISTS"

MAILGUN_ENDPOINT = "https://api.mailgun.net/v3/mg.thewbsproject.com"

AUTH_URL = "https://test-api.pm-empower.com"
AUTH_AUDIENCE = "https://pm-empower.us.auth0.com/api/v2/"
AUTH_DOMAIN = "pm-empower.us.auth0.com"

[env.test]
name = "pm-empower-api-test"
usage_model = "unbound"
workers_dev = false
routes = [
	{ pattern = "test-api.pm-empower.com/*", zone_name = "pm-empower.com" },
	{ pattern = "temp-api.pm-empower.com/*", zone_name = "pm-empower.com" }
]
kv_namespaces = [
  { binding = "KV_DATA", id = "6a8e3a3a07014e228d56aa7f28059ed2", preview_id = "6a8e3a3a07014e228d56aa7f28059ed2" },
]
r2_buckets = [
  { binding = "BUCKET_SNAPSHOTS", bucket_name = "snapshots-qa" }
]
[env.test.vars]
DEBUG = "false"
DATADOG_ENV = "test"
CORS_ORIGINS = "https://test.pm-empower.com"

MAILGUN_ENDPOINT = "https://api.mailgun.net/v3/mg.thewbsproject.com"

AUTH_AUDIENCE = "https://pm-empower.us.auth0.com/api/v2/"
AUTH_DOMAIN = "pm-empower.us.auth0.com"

[env.prod]
name = "pm-empower-api-prod"
usage_model = "unbound"
workers_dev = false
routes = [
	{ pattern = "api.pm-empower.com/*", zone_name = "pm-empower.com" }
]
kv_namespaces = [

  { binding = "KV_DATA", id = "408389bba37f437da346442f36b25a45", preview_id = "408389bba37f437da346442f36b25a45" },
]
r2_buckets = [
  { binding = "BUCKET_SNAPSHOTS", bucket_name = "snapshots-prod.com" }
]
[env.prod.vars]
DEBUG = "false"
DATADOG_ENV = "production"
CORS_ORIGINS = "https://app.pm-empower.com"

MAILGUN_ENDPOINT = "https://api.mailgun.net/v3/mg.thewbsproject.com"

AUTH_AUDIENCE = "https://pm-empower.us.auth0.com/api/v2/"
AUTH_DOMAIN = "pm-empower.us.auth0.com"

[dev]
port = 88
host = "web-api"
