name = "wbs-app"
account_id = "004dc1af737b22a8aa83b3550fa9b9d3"
compatibility_date = "2022-05-27"
usage_model = "unbound"
main = "dist/index.js"

[build]
command = "yarn run -s build"

[build.upload]
format = "modules"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[site]
bucket = "./public"

[env.dev]
name = "wbs-app-dev"
kv_namespaces = [
  { binding = "KV_AUTH" },
  { binding = "KV_DATA" },
]
r2_buckets = [
  { binding = "BUCKET_SNAPSHOTS" }
]
vars = { APP_INSIGHTS_KEY = "1a9b6a54-3afc-4ee5-8e17-3d109b834c55", DEBUG = "true" }

[env.prod]
name = "wbs-app-prod"
workers_dev = false
route = "https://app.thewbsproject.com/*"
kv_namespaces = [
  { binding = "KV_AUTH", id = "d59c9e5d23ed4a1783787b1b4e9aa213", preview_id = "92a843cb6f674b29aa29089f31ad5054" },
  { binding = "KV_DATA", id = "9020ff7ce374481285c71d9519942ccd", preview_id = "92a843cb6f674b29aa29089f31ad5054" },
]
r2_buckets = [
  { binding = "BUCKET_SNAPSHOTS", bucket_name = "snapshots-prod" }
]
vars = { CORS_URLS = "https://app.thewbsproject.com", APP_INSIGHTS_KEY = "5a16ddbc-8131-4627-8497-1c4977cb7730" }

[miniflare]
port = 88
watch = true
kv_persist = true
r2_persist = true
cache_persist = false
cache = false
https = true
actual_time = true
inaccurate_cpu = true
