name = "wbs-app"
type = "javascript"
zone_id = "5491aca876a47684c4b5025af0d4aa32"
account_id = "ce9999d7d59fce98a0bc0e7911cb6e1f"
webpack_config = "./workers-site/webpack.config.js"
compatibility_date = "2021-10-24"

[build]
command = "yarn && yarn run build"
[build.upload]
format = "service-worker"

[site]
bucket = "./public"
entry-point = "workers-site"

[env.dev]
vars = { APP_INSIGHTS_KEY = "1a9b6a54-3afc-4ee5-8e17-3d109b834c55", DEBUG = "true", TTL_MANIFEST = 33, TTL_JSSCSS = 33, TTL_ICONS = 33, TTL_IMAGES = 33, TTL_FONTS = 33, KV_BYPASS = "" }

[env.prod]
route = "https://www.thewbsproject.com/*"
vars = { CORS_URLS = "https://www.thewbsproject.com" }
