export enum NODE_CREATION_PAGES {
  DISCIPLINES = 'discipline',
  OTHER_FLAGS = 'flags',
  PHASE = 'phase',
  STARTER = 'starter',
  TAGS = 'tags',
  TITLE_DESCRIPTION = 'title',
}
export type NODE_CREATION_PAGES_TYPE =
  | NODE_CREATION_PAGES.DISCIPLINES
  | NODE_CREATION_PAGES.OTHER_FLAGS
  | NODE_CREATION_PAGES.PHASE
  | NODE_CREATION_PAGES.STARTER
  | NODE_CREATION_PAGES.TAGS
  | NODE_CREATION_PAGES.TITLE_DESCRIPTION;
