export enum NODE_CREATION_PAGES {
  STARTER = 'starter',
  TITLE_DESCRIPTION = 'title',
  PHASE = 'phase',
  DISCIPLINES = 'discipline',
  TAGS = 'tags',
}
export type NODE_CREATION_PAGES_TYPE =
  | NODE_CREATION_PAGES.STARTER
  | NODE_CREATION_PAGES.PHASE
  | NODE_CREATION_PAGES.DISCIPLINES
  | NODE_CREATION_PAGES.TITLE_DESCRIPTION
  | NODE_CREATION_PAGES.TAGS;
