export enum NODE_CREATION_PAGES {
  STARTER = 'starter',
  NAME_DESCRIPTION = 'name',
  CATEGORIES = 'categories',
}
export type NODE_CREATION_PAGES_TYPE =
  | NODE_CREATION_PAGES.STARTER
  | NODE_CREATION_PAGES.CATEGORIES
  | NODE_CREATION_PAGES.NAME_DESCRIPTION;
