# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Site Builder - v0.1

on:
  push:
    branches: ["v0.1"]
  pull_request:
    branches: ["v0.1"]

jobs:
  site_job:
    name: Site Deployment
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Setup Environment
        run: npm config set "@fortawesome:registry" https://npm.fontawesome.com/ && npm config set "//npm.fontawesome.com/:_authToken" $FA_TOKEN
        env:
          FA_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
      - name: Install Packages
        run: yarn --cwd site run setup
        env:
          FA_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
      - name: Build Site
        run: yarn --cwd site run publish

  worker_job:
    name: Worker Deployment
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install Packages
        run: yarn --cwd worker run setup
      - name: Build Worker
        run: yarn --cwd worker run build
